ISO/IEC FDIS 14496-15 6th edition
mp4ra/mp4ra.github.io pull request #121
Opened 2021-06-15 11:45 UTC by mhannuksela

This pull request contains the new four-character codes in ISO/IEC FDIS 14496-15 6th edition (document MDS20296, ISO/IEC JTC1 SC29 WG03 N00234), i.e. those that have been specified subsequent to 14496-15 5th edition Amd. 1. Most notably, the pull request contains the four-character codes for the ISO base media file format bindings of the Versatile Video Coding (VVC, ISO/IEC 23090-3) and the Essential Video Coding (EVC, ISO/IEC 23094-1), which are respectively specified in clauses 11 and 12 of ISO/IEC 14496-15 6th edition.

Some alphabetical ordering mistakes were also corrected in this pull request.

2021-06-23 07:35 UTC, podborski requested changes
Looks good to me. But the descriptions of few sample entry types should be improved in my opinion.

2021-06-23 15:57 UTC, dwsinger commented on CSV/sample-entries.csv
> +evs2,Essential Video Coding slice component track,Video,NALu Video,
yes, please let's try to avoid having multiple entries with the same exact text...

2021-07-13 18:11 UTC, mhannuksela commented on CSV/sample-entries.csv
> +vvs1,Versatile Video Coding,Video,NALu Video,
Done!

2021-07-13 18:11 UTC, mhannuksela commented on CSV/sample-entries.csv
> +evs2,Essential Video Coding slice component track,Video,NALu Video,
Done!

2021-07-13 19:49 UTC, podborski approved these changes

2021-07-15 14:17 UTC, merged